=== das-fbk/CollectiveAdaptationEngine/schemata/Ensemble.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://das.fbk.eu/Ensemble"
	xmlns:tns="http://das.fbk.eu/Ensemble" elementFormDefault="qualified" 
	xmlns:ns1="http://das.fbk.eu/DomainObject">
	

<import namespace="http://das.fbk.eu/DomainObject" schemaLocation="DomainObject.xsd" />
	
	<element name="ensemble">
		<complexType>
			<annotation>
				<documentation>Main type of an ensemble, defined by a name, a sequence
					of roles and a list of variables
				</documentation>
			</annotation>
			<sequence>
				<sequence>
				   <element name="role" type="tns:Role" minOccurs="1" maxOccurs="unbounded"/>
				</sequence>
				<element name="variable" type="NMTOKEN" minOccurs="0"
					maxOccurs="unbounded" />

			</sequence>
			<attribute name="name" type="string"></attribute>
		</complexType>
		
	</element>






	<complexType name="Role">
		<annotation>
			<documentation>role of an ensemble</documentation>
		</annotation>
		<sequence>
			<element name="domainObjectType" type="string" maxOccurs="1" minOccurs="1"/>
			<element name="solver" type="tns:Solver" maxOccurs="unbounded"
				minOccurs="0"></element>
			<element name="preferences" type="NMTOKEN" minOccurs="0"
					maxOccurs="unbounded" />
		</sequence>
		<attribute name="type" type="string"></attribute>
		<attribute name="id" type="string"></attribute>
	</complexType>
	
	
	<complexType name="Solver">
	<annotation>
			<documentation>solver of a role in an ensemble</documentation>
		</annotation>
			<sequence>
				<element name="issue" type="tns:Issue" minOccurs="1" maxOccurs="1"></element>
				<element name="solverCondition" type="string" minOccurs="1"
					maxOccurs="1" />	
				<element name="solution" type="tns:Solution" minOccurs="1" maxOccurs="unbounded">
				</element>
			</sequence>
			<attribute name="name" type="string" />
			<attribute name="selected" type="boolean" use="required"></attribute>
		</complexType>
	

	
	<complexType name="Issue">
		<annotation>
			<documentation>issue of a solver</documentation>
		</annotation>
		<sequence>
			<element name="issueType" type="string" maxOccurs="1" minOccurs="1">
			</element>
			<element name="issueCondition" type="string" maxOccurs="1" minOccurs="1"></element>
		</sequence>
	</complexType>
	
	<complexType name="Solution">
		<sequence>
			<element name="internalSolution" type="string" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="issue" type="tns:Issue" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="time" type="int"></attribute>
		<attribute name="cost" type="double"></attribute>
	</complexType>



	<attribute name="Name" type="string"></attribute>
</schema>

=== das-fbk/CollectiveAdaptationEngine/scenario/ALLOWEnsembles/ensembles/E4.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ensemble name="E4" xmlns:tns="http://das.fbk.eu/Ensemble" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://das.fbk.eu/Ensemble Ensemble.xsd ">
 
  <!--  CS -->
  <tns:role id="cs" type="CS">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    <!--  solution to possible collition -->
   <tns:solver name="S12" selected="true">
      <tns:issue>
        <tns:issueType>I6</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!-- Possible Collition -->
          <tns:issueType>I2</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
      </tns:solution>
    </tns:solver>
    
     <tns:solver name="S4" selected="true">
      <tns:issue>
        <tns:issueType>I2</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
          <tns:issueType>I10</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
      </tns:solution>
    </tns:solver>
    
    

    <tns:preferences>NMTOKEN</tns:preferences>
  </tns:role>
  
  <!-- H3 (Ground Station) -->
  <tns:role id="h3" type="H3">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    <tns:solver name="S17" selected="true">
      <tns:issue>
        <tns:issueType>I9</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!-- Possible Collition -->
        <tns:issueType>I6</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      </tns:solution>
    </tns:solver>
 
     <tns:preferences>NMTOKEN</tns:preferences>
  </tns:role>
   
  
  
   <!-- H2 (Ground Station) -->
  <tns:role id="h2" type="H2">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    <tns:solver name="S5" selected="true">
      <tns:issue>
        <tns:issueType>I10</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>
    
    
    <tns:solver name="S17" selected="true">
      <tns:issue>
        <tns:issueType>I10</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
          <tns:issueType>I12</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
      </tns:solution>
    </tns:solver>
    
    <tns:solver name="S18" selected="true">
      <tns:issue>
        <tns:issueType>I11</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
          <tns:issueType>I13</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
      </tns:solution>
    </tns:solver>
    
    
    <tns:preferences>NMTOKEN</tns:preferences>
  </tns:role>
   
   
   
    <!-- G1 (Guard) -->
  <tns:role id="g1" type="G1">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    <tns:solver name="S3" selected="true">
      <tns:issue>
        <tns:issueType>I2</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
         <tns:issue>
          <tns:issueType>I11</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
      </tns:solution>
    </tns:solver>
    
    
     <tns:issue>
        <!-- Drone manual mode should be activated -->
          <tns:issueType>I11</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
    
    <tns:solver name="S17" selected="true">
      <tns:issue>
        <tns:issueType>I10</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
          <tns:issueType>I12</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
      </tns:solution>
    </tns:solver>
    
    
    <tns:preferences>NMTOKEN</tns:preferences>
  </tns:role>
   
   
  <tns:variable>NMTOKEN</tns:variable>
</tns:ensemble>

=== das-fbk/CollectiveAdaptationEngine/scenario/ALLOWEnsembles/ensembles/Route1a.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ensemble name="Route1" xmlns:tns="http://das.fbk.eu/Ensemble" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://das.fbk.eu/Ensemble Ensemble.xsd ">
  <!--  ROUTE MANAGER RM1 -->
  <tns:role id="rm1" type="RM1">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
    <!--Solve FB Route Interrupted with PickUp Point Revised-->
    <tns:solver name="S1" selected="true">
      <tns:issue>
        <tns:issueType>DriverNotifyRouteInterrupted</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!--  communicate to the Driver to change the route path -->
        <tns:issueType>DriverChangePath</tns:issueType>
        <tns:issueCondition>Exist</tns:issueCondition>
      </tns:issue>
      <tns:issue>
        <!--  communicate to Passenger to change the pickup point -->
        <tns:issueType>ChangePickUpPoint</tns:issueType>
        <tns:issueCondition>Forall</tns:issueCondition>
      </tns:issue>
      </tns:solution>
    </tns:solver>
   
    
    <!--Solve FB Route Interrupted with Change Time-->
    <tns:solver name="S2" selected="true">
      <tns:issue>
        <tns:issueType>DriverNotifyRouteInterrupted</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!--  communicate to the Driver to change the route path -->
        <tns:issueType>DriverChangePath</tns:issueType>
        <tns:issueCondition>Exist</tns:issueCondition>
      </tns:issue>
      <tns:issue>
        <!--  communicate to Passenger to change the pickup time -->
        <tns:issueType>ChangePickUpTime</tns:issueType>
        <tns:issueCondition>Forall</tns:issueCondition>
      </tns:issue>
      </tns:solution>
    </tns:solver>
    
    
    
     <!--Solve FB Route Interrupted with PickUp Point and PickUp Time Revised-->
    <tns:solver name="S3" selected="true">
      <tns:issue>
        <tns:issueType>DriverNotifyRouteInterrupted</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!--  communicate to the Driver to change the route path -->
        <tns:issueType>DriverChangePath</tns:issueType>
        <tns:issueCondition>Forall</tns:issueCondition>
      </tns:issue>
      <tns:issue>
        <!--  communicate to Passenger to change the pickup point -->
        <tns:issueType>ChangePickUpPoint</tns:issueType>
        <tns:issueCondition>Exist</tns:issueCondition>
      </tns:issue>
      <tns:issue>
        <!--  communicate to Passenger to change the pickup time -->
        <tns:issueType>ChangePickUpTime</tns:issueType>
        <tns:issueCondition>Exist</tns:issueCondition>
      </tns:issue>
      </tns:solution>
    </tns:solver>
    

    </tns:role>
    
   <!--  DRIVER D1 -->
  <tns:role id="d1" type="D1">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
    <!--Update route path (Local)-->
    <tns:solver name="S4" selected="true">
      <tns:issue>
        <tns:issueType>DriverChangePath</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>

    </tns:role>
    
   <!--  PASSENGER P1 -->
  <tns:role id="p1" type="P1">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
<!--change pickup point (Local)-->
    <tns:solver name="S5" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpPoint</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>
     <!--change pickup time (Local)-->
    <tns:solver name="S6" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpTime</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>

    </tns:role>
    
    
    <!--  PASSENGER P2 -->
  <tns:role id="p2" type="P2">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
<!--change pickup point (Local)-->
    <tns:solver name="S5" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpPoint</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>
     <!--change pickup time (Local)-->
    <tns:solver name="S6" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpTime</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>
    </tns:role>
    
   <!--  PASSENGER P3 -->
  <tns:role id="p3" type="P3">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
<!--change pickup point (Local)-->
    <tns:solver name="S5" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpPoint</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>
     <!--change pickup time (Local)-->
    <tns:solver name="S6" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpTime</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>

    </tns:role>
    
    
     <!--  PASSENGER P4 -->
  <tns:role id="p4" type="P4">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    

  <!--change pickup point (Local)-->
    <tns:solver name="S5" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpPoint</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>
     <!--change pickup time (Local)-->
    <tns:solver name="S6" selected="true">
      <tns:issue>
        <tns:issueType>ChangePickUpTime</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
      </tns:solution>
    </tns:solver>


    </tns:role>
   
  <tns:variable>NMTOKEN</tns:variable>
</tns:ensemble>

=== das-fbk/CollectiveAdaptationEngine/schemata/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ensemble name="" xmlns:tns="http://das.fbk.eu/Ensemble" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://das.fbk.eu/Ensemble Ensemble.xsd ">
  <tns:role id="" type="">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    <tns:solver name="" selected="true">
      <tns:issue>
        <tns:issueType>tns:issueType</tns:issueType>
        <tns:issueCondition>tns:issueCondition</tns:issueCondition>
      </tns:issue>
      <tns:solverCondition>tns:solverCondition</tns:solverCondition>
      <tns:solution cost="0.0" name="" time="0">
        <tns:internalSolution>tns:internalSolution</tns:internalSolution>
        <tns:issue>
          <tns:issueType>tns:issueType</tns:issueType>
          <tns:issueCondition>tns:issueCondition</tns:issueCondition>
        </tns:issue>
      </tns:solution>
    </tns:solver>
    <tns:preferences>NMTOKEN</tns:preferences>
  </tns:role>
  <tns:variable>NMTOKEN</tns:variable>
</tns:ensemble>

=== das-fbk/CollectiveAdaptationEngine/src/main/resources/scenario/ALLOWEnsembles/Review/ensembles/FlexiBusMngmt.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ensemble name="FlexiBusMngmt" xmlns:tns="http://das.fbk.eu/Ensemble" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://das.fbk.eu/Ensemble Ensemble.xsd ">
  <!--  ROUTE MANAGER RMA -->
 <tns:role id="RouteManagement_1" type="RouteManagement_1">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
    <!--Forward the Issue to Assign Passengers of RouteA to another Route of the FBC-->
    <tns:solver name="ManagePassengers" selected="true">
      <tns:issue>
        <tns:issueType>AddPassengersRouteA</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL1">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!--  communicate to the RM of A to allocate Passengers of ROute B in A -->
        <tns:issueType>AllocatePassengersRouteA</tns:issueType>
        <tns:issueCondition>Exist</tns:issueCondition>
      </tns:issue>
      </tns:solution>
    </tns:solver>
  </tns:role>
  
  
  <!--  ROUTE MANAGER RMB -->
 <tns:role id="RouteManagement_2" type="RouteManagement_2">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
    <!--Manage the assignment of new passengers from another route (RouteA)-->
    <tns:solver name="AddPassengers" selected="true">
      <tns:issue>
        <tns:issueType>AddPassengersRouteB</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL1">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!--  communicate to the Driver the new passengers -->
        <tns:issueType>ChangeNumOfPassengers</tns:issueType>
        <tns:issueCondition>Exist</tns:issueCondition>
      </tns:issue>
      </tns:solution>
    </tns:solver>
  </tns:role>
    
   <!--  Flexi Bus Company -->
  <tns:role id="FBC1" type="FBC">
    <tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
    
    <!--Allocate Passengers of B To ROUTE A-->
    <tns:solver name="AllocatePassenger" selected="true">
      <tns:issue>
        <tns:issueType>AssignPassengerOfB</tns:issueType>
        <tns:issueCondition></tns:issueCondition>
      </tns:issue>
      <tns:solverCondition></tns:solverCondition>
      <tns:solution name="SOL">
        <tns:internalSolution>internalSolution</tns:internalSolution>
        <tns:issue>
        <!--  communicate to the RouteA To add Passengers -->
        <tns:issueType>AddPassengersRouteA</tns:issueType>
        <tns:issueCondition>Exist</tns:issueCondition>
      </tns:issue>
     </tns:solution>
     </tns:solver>
 
    </tns:role>
    
  
    
   
  <tns:variable>NMTOKEN</tns:variable>
</tns:ensemble>

=== das-fbk/CollectiveAdaptationEngine/src/main/resources/scenario/ALLOWEnsembles/Review/ensembles/RouteB.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ensemble name="RouteB" xmlns:tns="http://das.fbk.eu/Ensemble" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://das.fbk.eu/Ensemble Ensemble.xsd ">
  
	<!--  ROUTE MANAGER RMB -->
	<tns:role id="RouteManagement_2" type="RouteManagement_2">
		<tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>

		<!--Solve RouteBlockes Issue generated by the Driver with ReRoute for the 
			bus and Exit for the passenger -->
		<tns:solver name="PassengerReAssignment" selected="true">
			<tns:issue>
				<tns:issueType>RouteBlocked</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution name="SOL1">
				<tns:internalSolution>Nothing</tns:internalSolution>
				<tns:issue>
					<!-- communicate to the Driver to change the route path dropping a PP -->
					<tns:issueType>ChangePathDropPP</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
				<tns:issue>
					<!-- communicate to Passenger to plan alone exiting the ensemble -->
					<tns:issueType>ExitAndChangeRoutePP</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
				<tns:issue>
					<!-- Ask Help TO FBC to assign the passenger P6-->
					<tns:issueType>AssignPassengerOfB</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
				
			</tns:solution>
		</tns:solver>
		
		<tns:solver name="WalkAndDropPP" selected="true">
			<tns:issue>
				<tns:issueType>RouteBlocked</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution name="SOL3">
				<tns:internalSolution>Nothing</tns:internalSolution>
				<tns:issue>
					<!-- communicate to the Driver to change the route path dropping a PP -->
					<tns:issueType>ChangePathDropPP</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
				<tns:issue>
					<!-- communicate to Passenger to plan alone exiting the ensemble -->
					<tns:issueType>ExitAndRePlanWalk</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
			</tns:solution>
		</tns:solver>
		
		<tns:solver name="UseCarAndDropPP" selected="true">
			<tns:issue>
				<tns:issueType>RouteBlocked</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution name="SOL2">
				<tns:internalSolution>Nothing</tns:internalSolution>
				<tns:issue>
					<!-- communicate to the Driver to change the route path dropping a PP -->
					<tns:issueType>ChangePathDropPP</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
				<tns:issue>
					<!-- communicate to Passenger to plan alone exiting the ensemble -->
					<tns:issueType>ExitAndRePlanCar</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
			</tns:solution>
		</tns:solver>

   
    </tns:role>
    
   <!-- DRIVER B -->
	<tns:role id="FlexibusDriver_28" type="FlexibusDriver_28">
		<tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>

		<!--Communicate Route Blocked -->
		<tns:solver name="RouteBlocked" selected="true">
			<tns:issue>
				<tns:issueType>RouteBlocked</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution name="SOL">
				<tns:internalSolution>Nothing</tns:internalSolution>
				<tns:issue>
					<!-- communicate to the Driver to change the route path -->
					<tns:issueType>RouteBlocked</tns:issueType>
					<tns:issueCondition>Exist</tns:issueCondition>
				</tns:issue>
			</tns:solution>
		</tns:solver>
		<!--Change  Route Removing PP -->
	<tns:solver name="ChangeRouteDropPP" selected="true">
			<tns:issue>
				<tns:issueType>ChangePathDropPP</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution name="SOL">
				<tns:internalSolution>ChangePathDropPP2</tns:internalSolution>
			</tns:solution>
		</tns:solver>
</tns:role>

<!-- PASSENGER P4 -->
	<tns:role id="RoutePassenger_64" type="RoutePassenger_64">
		<tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>

			
	<!--P4 Exit and Change-->
		<tns:solver name="ExitAndChange" selected="true">
			<tns:issue>
				<tns:issueType>ExitAndChangeP4</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution cost="3" name="sol" time="10">
				<tns:internalSolution>ExitAndChange</tns:internalSolution>
			</tns:solution>
		</tns:solver>	 
	</tns:role>

	<!-- PASSENGER P4 BIS -->
	<tns:role id="RoutePassenger_69" type="RoutePassenger_69">
		<tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>
		
	<!--P4 BIS Exit and Change-->
		<tns:solver name="ExitAndChange" selected="true">
			<tns:issue>
				<tns:issueType>ExitAndChangeP2</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution cost="3" name="sol" time="10">
				<tns:internalSolution>ExitAndChange</tns:internalSolution>
			</tns:solution>
		</tns:solver>	
		
				
	</tns:role>

	<!-- PASSENGER P6 -->
	<tns:role id="USER_6" type="RoutePassenger_74">
		<tns:domainObjectType>tns:domainObjectType</tns:domainObjectType>

			
	<!--P6 Exit and Change Route PP-->
		<tns:solver name="ExitAndChange" selected="true">
			<tns:issue>
				<tns:issueType>ExitAndChangeRoutePP</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution cost="12" name="sol" time="25">
				<tns:internalSolution>ExitAndChangeRoutePP</tns:internalSolution>
			</tns:solution>
		</tns:solver>	
		
		<!--P6 go directly by car-->
		<tns:solver name="ExitAndRePlanCar" selected="true">
			<tns:issue>
				<tns:issueType>ExitAndRePlanCar</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution cost="12" name="sol" time="25">
				<tns:internalSolution>ExitAndRePlanCar</tns:internalSolution>
			</tns:solution>
		</tns:solver>
		
		<!--P6 go directly by walk-->
		<tns:solver name="ExitAndRePlanWalk" selected="true">
			<tns:issue>
				<tns:issueType>ExitAndRePlanWalk</tns:issueType>
				<tns:issueCondition></tns:issueCondition>
			</tns:issue>
			<tns:solverCondition></tns:solverCondition>
			<tns:solution cost="0" name="sol" time="75">
				<tns:internalSolution>ExitAndRePlanWalk</tns:internalSolution>
			</tns:solution>
		</tns:solver>
		 
	</tns:role>
			
  <tns:variable>NMTOKEN</tns:variable>
</tns:ensemble>
