=== das-fbk/CollectiveAdaptationEngine/schemata/preferences.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/preferences" 
xmlns:tns="http://www.example.org/preferences" elementFormDefault="qualified">

<element name="routes">
		<annotation>
			<documentation>Preferences</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element name="preferences" maxOccurs="1" minOccurs="1">
					<complexType>
						<sequence>
							<element name="TravelTimeWeight" type="double"></element>
							<element name="CostWeight" type="double"></element>
							<element name="WalkingDistanceWeight" type="double"></element>
							<element name="NumberOfChangesWeight" type="double"></element>
							<element name="ReliabilityCostWeight" type="double"></element>
							<element name="UnsatisfiedSafetyPreferenceWeight" type="double"></element>
							<element name="WillingnessToShareDataWeight" type="double"></element>
							<element name="MaximumTravelDuration" type="int"></element>
							<element name="MaximumCost" type="double"></element>
							<element name="MaximumWalkingDistance" type="double"></element>
							<element name="MaximumReliabilityCost" type="double"></element>
							<element name="MaximumNumberOfChanges" type="int"></element>
						</sequence>
						<attribute type="string" name="color" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>


</schema>

=== das-fbk/CollectiveAdaptationEngine/schemata/P1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:routes xmlns:tns="http://www.example.org/preferences" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/preferences preferences.xsd ">
  <tns:preferences>
    <tns:TravelTimeWeight>0.0</tns:TravelTimeWeight>
    <tns:CostWeight>0.0</tns:CostWeight>
    <tns:WalkingDistanceWeight>0.0</tns:WalkingDistanceWeight>
    <tns:NumberOfChangesWeight>0.0</tns:NumberOfChangesWeight>
    <tns:ReliabilityCostWeight>0.0</tns:ReliabilityCostWeight>
    <tns:UnsatisfiedSafetyPreferenceWeight>0.0</tns:UnsatisfiedSafetyPreferenceWeight>
    <tns:WillingnessToShareDataWeight>0.0</tns:WillingnessToShareDataWeight>
    <tns:MaximumTravelDuration>0</tns:MaximumTravelDuration>
    <tns:MaximumCost>0.0</tns:MaximumCost>
    <tns:MaximumWalkingDistance>0.0</tns:MaximumWalkingDistance>
    <tns:MaximumReliabilityCost>0.0</tns:MaximumReliabilityCost>
    <tns:MaximumNumberOfChanges>0</tns:MaximumNumberOfChanges>
  </tns:preferences>
</tns:routes>
